import Head from 'next/head'
import { getUserId, getUsers } from '../lib/slice/testSlice';
import { wrapper } from '../lib/store'
import { useDispatch, useSelector } from 'react-redux';
import { useEffect } from 'react';
export default function Home() {
  const dispatch = useDispatch()
  const selector = useSelector(state => state.productSlice)
  return (
    <div>
      <Head>
        <title>RTK-NextJs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className='w-full h-[4rem] bg-purple-500 flex justify-start'>
      <p className='text-white'>RTK</p>
    </div>
    

    
    </div>
  )
}



export const getServerSideProps = wrapper.getServerSideProps(store => async ({req, res}) => {
 await store.dispatch(getUsers());
 await store.dispatch(getUserId(1))
});